### ISSUE TITLE
Уебсайтът не работи от над 20 дни

### ISSUE THREAD

**Issue by TripleG** [Ceci2003/BeekeeperAssistant#1]
Здравейте момчета,

Мой приятел е използвал вашия сайт от около 2 години.
Може ли да ми дадете информация дали се очаква да пуснете сайтът да работи отново?
И ако не - има ли възможност да експортнете базата за даден юзър?

Благодаря!

**Comment by Ceci2003** [comment]
Здравейте,

Поради технически причини, платформата е временно неактивна. Съвсем скоро всичко ще бъде възстановено отново!
Моля за разбиране.

Поздрави!

**Comment by Ceci2003** [comment]
Здравейте,
Сайтът вече е възстановен. Извиняваме се за причиненото неудобство!

Поздрави!
